s=set()
n=input("Enter number1:")
s.add(int(n))
n=input("Enter number2:")
s.add(int(n))
n=input("Enter number3:")
s.add(int(n))
n=input("Enter number4:")
s.add(int(n))
n=input("Enter number5:")
s.add(int(n))
n=input("Enter number6:")
s.add(int(n))
n=input("Enter number7:")
s.add(int(n))
n=input("Enter number8:")
s.add(int(n))
print(s)